name: Run Skribos

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get branch name
      run: echo ::set-output name=reference::${GITHUB_REF:11}
      id: branch
    - name: Run Skribos
      uses: leonidlezner/skribos@master
      with:
        args: dist/${{ steps.branch.outputs.reference }} skribos.yml
    - name: Deploy to Github Pages
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: dist
        keep_history: true
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}